<a href="https://colab.research.google.com/github/HLCarbon/DeepLearning/blob/main/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning Tensorflow fundamentals

## Introduction

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


### Create tensor with tf.constant()

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of the vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[7,10],
                      [7,10]])

In [7]:
# Check dimension of matrix
matrix.ndim

2

In [8]:
# Create another matrix with different type

another_matrix = tf.constant([[10., 7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# Check dimension of another_matrix
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# Check dimension of tensor
tensor.ndim

3

**Scalar**: A single number

**Vector**: a number with directions

**Matrix**: a 2-dimensional array of number, like a table

**Tensor**: an n-dimensional array of numbers.

### tf.Variable

In [12]:
# Create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Changing a value in a changeable_tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [14]:
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [16]:
# Shuffle tensor
tf.random.set_seed(42)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [17]:
tf.ones([10,7], dtype = tf.int8)

<tf.Tensor: shape=(10, 7), dtype=int8, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int8)>

In [18]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [19]:
# NumPy array to tensors
import numpy  as np
numpy_A = np.arange(1,25, dtype = np.int32)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

### Get information from tensors

In [20]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
# Get various attributes from tensor

print('Datatyoe of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the -1 axis:', rank_4_tensor.shape[-1])
print('Total elements:', tf.size(rank_4_tensor).numpy())

Datatyoe of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the -1 axis: 5
Total elements: 120


### Indexing tensors

In [22]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [23]:
# Create rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [24]:
# Add extra dimensions
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [25]:
# Alterantive
tf.expand_dims(rank_2_tensor, axis = -1) # '-1' means expand the last axis. Should be the same as above

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (operating with tensors)

In [26]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [27]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [28]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

In [29]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Rules for matrices multiplication

* The inner dimensions must match (ex: [3,2] and [2,3])
* The resulting matrix has the shape of the external dimensions

In [30]:
new_tensor = tf.constant([[1,2],
                          [3,4],
                          [5,6]])

In [31]:
new_tensor, tf.transpose(new_tensor), tf.reshape(new_tensor, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [32]:
# Perform the dot product on X and Y(requires X or Y to be transposed)
tf.tensordot(tf.transpose(new_tensor), new_tensor, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

In [33]:
#Reduce precision
b = tf.constant([1.7,7.4])

In [36]:
b = tf.cast(b, dtype = tf.float16)
b.dtype

tf.float16

### Aggregating tensors

In [38]:
# Getting the absolute values
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [42]:
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([91, 58, 58, 75, 27, 44, 25, 81, 25, 20, 38, 85, 44, 12, 47, 77,  7,
       59, 98,  1, 98, 18, 95, 42, 75, 94, 28,  6, 61, 55, 75, 14, 35, 32,
        5, 50,  5, 83, 92, 37, 87, 68,  8, 62, 87, 67, 76, 64,  7, 83])>

In [48]:
print(tf.reduce_min(E))
print(tf.reduce_max(E))
print(tf.reduce_mean(E))
print(tf.reduce_sum(E))
E = tf.cast(E, dtype = np.float16)
print(tf.math.reduce_std(E))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(98, shape=(), dtype=int64)
tf.Tensor(51, shape=(), dtype=int64)
tf.Tensor(2581, shape=(), dtype=int64)
tf.Tensor(30.12, shape=(), dtype=float16)


### Find positional maximum and minimum

In [53]:
print('Maximum index:', tf.argmax(E))
print('Minimum index:', tf.argmin(E))

Maximum index: tf.Tensor(18, shape=(), dtype=int64)
Minimum index: tf.Tensor(19, shape=(), dtype=int64)


### Squeezing a tensor

In [56]:
#Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [58]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensor

In [62]:
some_list = [0,1,2,3]

#One hot encode
tf.one_hot(some_list, depth = 4, on_value = 'hello', off_value = 'world')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hello', b'world', b'world', b'world'],
       [b'world', b'hello', b'world', b'world'],
       [b'world', b'world', b'hello', b'world'],
       [b'world', b'world', b'world', b'hello']], dtype=object)>

In [63]:
np.array(E)

array([91., 58., 58., 75., 27., 44., 25., 81., 25., 20., 38., 85., 44.,
       12., 47., 77.,  7., 59., 98.,  1., 98., 18., 95., 42., 75., 94.,
       28.,  6., 61., 55., 75., 14., 35., 32.,  5., 50.,  5., 83., 92.,
       37., 87., 68.,  8., 62., 87., 67., 76., 64.,  7., 83.],
      dtype=float16)

In [66]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
print('numpy_J dtype:' ,numpy_J.dtype)
print('tensor_J dtype:', tensor_J.dtype)

numpy_J dtype: <dtype: 'float64'>
tensor_J dtype: <dtype: 'float32'>
